#!/bin/bash

# create git tag first
TAG=$1
#echo Tag $TAG
git tag $TAG
git push --tags

# now milestone
ENDPOINT=https://github.ibm.com/api/v3

# Yes, this is insanity complexity
REPO=`echo $(git remote get-url origin) | sed -r 's/.+\:(.+)\.git/\1/g'`
#echo Repo $REPO

DATA="{\"title\":\"$TAG\"}"
#echo Data $DATA
curl -s -u "$GIT_USER:$GIT_TOKEN" $ENDPOINT/repos/$REPO/milestones -d $DATA