#!/bin/bash

# make sure expected environment variables available
if [[ -z "$GITHUB_USER" ]] || [[ -z "$GITHUB_TOKEN" ]]
then
	echo "Missing GITHUB_USER or GITHUB_TOKEN environment variables"
	exit 1
fi

# make sure expected command-line parameters
if [[ -z "$1" ]] 
then
	echo "Usage: gtm <tag-name>"
	exit 1
fi

# create git tag first
TAG=$1
#echo Tag $TAG
git tag $TAG
git push origin $TAG

# now milestone
#ENDPOINT=https://github.ibm.com/api/v3
ENDPOINT=https://github.kyndryl.net/api/v3

# Yes, this is insanity complexity
REPO=`echo $(git remote get-url origin) | sed -r 's/.+\:(.+)\.git/\1/g'`
#echo Repo $REPO

DATA="{\"title\":\"$TAG\"}"
#echo Data $DATA
curl -sS -u "$GITHUB_USER:$GITHUB_TOKEN" $ENDPOINT/repos/$REPO/milestones -d $DATA
