#!/bin/bash

# make sure expected environment variables available
if [[ -z "$GIT_USER" ]] || [[ -z "$GIT_TOKEN" ]]
then
	echo "Missing GIT_USER or GIT_TOKEN environment variables"
	exit 1
fi

# make sure expected command-line parameters
if [[ -z "$1" ]] 
then
	echo "Usage: gitag <tag-name>"
	exit 1
fi

# create git tag first
TAG=$1
#echo Tag $TAG
git tag $TAG
git push origin $TAG

# now milestone
ENDPOINT=https://github.ibm.com/api/v3

# Yes, this is insanity complexity
REPO=`echo $(git remote get-url origin) | sed -r 's/.+\:(.+)\.git/\1/g'`
#echo Repo $REPO

DATA="{\"title\":\"$TAG\"}"
#echo Data $DATA
curl -sS -u "$GIT_USER:$GIT_TOKEN" $ENDPOINT/repos/$REPO/milestones -d $DATA